# Generated by Django 4.1.3 on 2023-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_stattrak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skin_float',
            field=models.FloatField(default=0.05),
        ),
    ]
