# Generated by Django 4.1.3 on 2023-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_weapon_is_stattrak_weapon_price_weapon_skin_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('rifle', 'RIFLE'), ('knife', 'KNIFE'), ('heavy', 'HEAVY'), ('pistol', 'PISTOL'), ('smg', 'SMG')], default='green', max_length=6),
        ),
    ]
