# Generated by Django 4.1.3 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_weapon_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='skin_float',
            field=models.FloatField(default=0.0),
        ),
    ]
