# Generated by Django 4.1.3 on 2023-03-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_weapon_skin_float'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['price', 'skin_name']},
        ),
    ]
