# Generated by Django 4.1.7 on 2023-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_customer_weapontest_customer_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontest',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='WeaponTest',
        ),
    ]
