# Generated by Django 4.1.7 on 2023-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_weapontest_seller_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
